### ISSUE TITLE
my nodemcu code is hanging 

### ISSUE THREAD

**Issue by ahmdgamaljimy95** [jbuszkie/HTTPSRedirect#4]
im using nodemcu and im try to connect my esp8266 to google sheet to
read and write to the sheet.
im using arduino ota to update my code.
the software is working fine for only one day and half for maximum
period of time and then my nodemcu hang and no serial data printed or
code execution except the arduino ota.
i have this issue one month ago i need your help please.

**Comment by jbuszkie** [comment]
I would go to the original author is mine is just a copy. https://github.com/electronicsguy/ESP8266.git
You might get help over there.
